# Site settings
title: Breaklights
description: 'ATX Punk Rock'
url: 'http://www.breaklightsatx.com'
baseurl: ''
google_analytics: 'UA-91091503-1'
disqus_shortname: 'breaklights'

author:
  name: 'Breaklights'
  email: breaklightsband@gmail.com
  #twitter_username: joshgerdes
  facebook_username: breaklights
  instagram_username: breaklights
  bandcamp_username: breaklights
  #github_username:  joshgerdes
  #linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jekyll-seo-tag']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
